Update dependencies to latest versions and refactor.
Running unit tests with the original dependencies results in the error
"Error: Cannot find module 'weak'". Updating the <phantomjs-node> module
resolves this error. However, <phantomjs-node> completely changed
its API in the newer versions. Updating this dependency required a
substantial refactoring of the CaptureJS code away from callbacks to
a structure that uses promises. Also, the configuration object
no longer supports port settings though there is a PhantomJS CLI
command that can specify a proxy address and port.

All other outdated dependencies were updated to bring the entire codebase
up to date. Additionally, NPM shinkwrap is now part of the repository
in order to lock the sub-dependency tree.

See the following link for further details concerning the original error:

http://stackoverflow.com/questions/23571499/node-js-and-phantomjs-cannot-find-module-weak